#!/usr/bin/env bash

set -eo pipefail

get_filesystem_type () {
  if [ -x "$(command -v diskutil)" ]; then
    printf $(diskutil info / | grep 'Type (Bundle)' | awk -F':' '{ print $2 }' | tr -d '[:space:]')
  else
    printf "other"
  fi
}

install_nix () {
  local filesystem_type=$(get_filesystem_type)
  local args=()

  if ! [ $SINGLE_USER == "true" ]; then
    args+=(--daemon)
  fi

  if [ $filesystem_type == "apfs" ]; then
    args+=(--darwin-use-unencrypted-nix-store-volume)
  fi

  sh <(curl -L https://nixos.org/nix/install) ${args[@]}

  . "$HOME/.nix-profile/etc/profile.d/nix.sh"
}

move_old () {
  if [ -f $1 ]; then
    echo "WARN: $1 found, moving to $1.old"

    mv $1 $1.old
  fi
}

install_home_manager () {
  source $PWD/nixpkgs/config.sh

  move_old $HOME/.bashrc
  move_old $HOME/.gitconfig

  mkdir -p ~/.config
  nix-shell -p coreutils --run "ln -sfT $PWD/nixpkgs $HOME/.config/nixpkgs"

  nix-shell '<home-manager>' -A install
}

change_shell () {
  sudo bash -c "echo $(which bash) >> /etc/shells"
  sudo chsh -s $(which bash) $(whoami)
}

if ! [ -x "$(command -v nix)" ]; then
  echo "Installing Nix"

  install_nix
else
  echo "Nix already installed, skipping"
fi

if ! [ -x "$(command -v home-manager)" ]; then
  echo "Installing Home Manager"

  install_home_manager
else
  echo "Home Manager already installed, skipping"
fi

if ! [ $SHELL == $(which bash) ]; then
  echo "Changing shell to $(which bash)"

  change_shell
else
  echo "Shell already set to $(which bash), skipping"
fi
