#! /usr/bin/env bash

mkdir -p ~/.config/nixpkgs
rm -rf ~/.config/nixpkgs/*
cp -R nix/* ~/.config/nixpkgs/

nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
nix-channel --update

NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH \
  nix-shell '<home-manager>' -A install --command "home-manager switch"
